name: copy post to database
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install external repo
      uses: actions/checkout@v2
      with:
        repository: purduehackers/ph-wiki-post-loader
        path: ./ph-wiki-post-loader
    - name: Install deps
      run: |
        cd ./ph-wiki-post-loader
        yarn install
        yarn run start

